name: Deploy to remote server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo wget https://github.com/danielcregg/pwa-lighthouse-specs/archive/refs/heads/main.zip -P /var/www/html/ && sudo apt install unzip && sudo unzip /var/www/html/main.zip && sudo mv -f pwa-lighthouse-specs-main/* . && sudo rm -rf main* pwa-lighthouse-specs-main/"
    - name: cleanup
      run: rm -rf ~/.ssh
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: rsync with password
      run: sudo sshpass -p 'login2VM1234' rsync -re ${{ github.workspace }}/* root@68.219.107.109:/var/www/html
    - name: Deploy to Server
      uses: inf166/action-sshpass-rsync@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        pass: ${{ secrets.DEPLOY_PASS }}
        local: ${{ github.workspace }}/*
        remote: /var/www/html/
