name: Deploy Website to Remote Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to remote server
      run: |
        rsync -r --delete-after --quiet ${{ github.workspace }}/* azureuser@${{ variables.MYVM }}:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
